# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-lienar-regression-tutorial',
                'doc_host': 'https://SpuriusSergius.github.io',
                'git_url': 'https://github.com/SpuriusSergius/nbdev-lienar-regression-tutorial',
                'lib_path': 'nbdev_lienar_regression_tutorial'},
  'syms': { 'nbdev_lienar_regression_tutorial.core': { 'nbdev_lienar_regression_tutorial.core.foo': ( 'core.html#foo',
                                                                                                      'nbdev_lienar_regression_tutorial/core.py')}}}